`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: 
// Engineer: 
// 
// Create Date: 2021/11/10 23:27:17
// Design Name: 
// Module Name: loopback_top
// Project Name: 
// Target Devices: 
// Tool Versions: 
// Description: 
// 
// Dependencies: 
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
// 
//////////////////////////////////////////////////////////////////////////////////


module loopback_top(
    input   clk,
    input   rst,
    input   uart_rx,
    input   rx_switch,
    input   tx_switch,
    output  uart_tx,
    output  led
    );
    //parameter for uart & Memory
    parameter   BAUD_RATE = 115_200;
    parameter   CLOCK_RATE = 50_000_000;
    parameter   MEMORY_DEPTH = 128*128; //the parameter should be set as the size of image
    
    //uart_rx signal
    wire    [7:0]   uart_rx_data;
    wire    uart_rx_ready;
    
    //uart_tx signal
    wire    [7:0]   uart_tx_data;
    wire    uart_tx_pop;
    wire    uart_tx_on;    
    
    //memory signal
    wire    memory_en;
    wire    memory_write_en;
    wire    [14:0]  memory_addr;
    wire    [7:0]   memory_data_in;
    wire    [7:0]   memory_data_out;

    wire clk_50MHz;

    //Clock Conversion Module is added
    //Clock frequency Requirement for UART is 50 MHz 
    //100MHz clock generated by FPGA is converted to 50MHz, here. 
    ClockDivider#(
        .divide_rate(2)
    ) clk_div (
        .clk_in(clk),
        .rst(rst),
        .clk_out(clk_50MHz)
    );

    uart_rx #(
        .BAUD_RATE(BAUD_RATE),
        .CLOCK_RATE(CLOCK_RATE)
    )   Uuart_rx_0(
        .clk_rx(clk_50MHz),       // Clock input
        .rst_clk_rx(rst),   // Active HIGH reset - synchronous to clk_rx
        .rxd_i(uart_rx),        // RS232 RXD pin - Directly from pad
        .rx_data(uart_rx_data),      // 8 bit data output
        .rx_data_rdy(uart_rx_ready)  // Ready signal for rx_data
    );
    
    uart_tx #(
        .BAUD_RATE(BAUD_RATE),
        .CLOCK_RATE(CLOCK_RATE)
    )   Uuart_tx_0(
        .clk_tx(clk_50MHz),          // Clock input
        .rst_clk_tx(rst),      // Active HIGH reset - synchronous to clk_tx
       
        .char_fifo_empty(!uart_tx_on), // Empty signal from char FIFO (FWFT)
        .char_fifo_dout(uart_tx_data),  // Data from the char FIFO
        .char_fifo_rd_en(uart_tx_pop), // Pop signal to the char FIFO
       
        .txd_tx(uart_tx)           // The transmit serial signal
    );

    // TO DO : connect the IO ports of below modules
    blk_mem_gen_0 Ublk_mem_gen_0
    (
        .clka(clk_50MHz),
        .ena(memory_en),            // TO DO
        .wea(memory_write_en),      // TO DO
        .addra(memory_addr),        // TO DO
        .dina(memory_data_in),      // TO DO
        .douta(memory_data_out)     // TO DO
    );
    memory_control#(
        .MEMORY_DEPTH(MEMORY_DEPTH)
    ) Umemory_control(
        .rst(rst),
        .clk(clk_50MHz),
        .rx_switch(rx_switch),      // TO DO
        .tx_switch(tx_switch),      // TO DO
        .led(led),
    //uart_rx signal
        .uart_rx_data(uart_rx_data),    // TO DO
        .uart_rx_ready(uart_rx_ready),  // TO DO
    //uart_tx signal
        .uart_tx_data(uart_tx_data),    // TO DO
        .uart_tx_pop(uart_tx_pop),      // TO DO
        .uart_tx_on(uart_tx_on),        // TO DO
    //memory signal
        .memory_en(memory_en),          // TO DO
        .memory_write_en(memory_write_en),  // TO DO
        .memory_addr(memory_addr),  // TO DO
        .memory_data_in(memory_data_in),    // TO DO
        .memory_data_out(memory_data_out)   // TO DO
    );

    
endmodule
